apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dev
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: "semver:*"
spec:
  releaseName: dev
  chart:
    git: git@github.com:kingdonb/flux-getting-started
    path: chart
    ref: master
  values:
    replicaCount: 2
    image:
      repository: registry.cloud.okteto.net/kingdonb/hello-world
      tag: golang
